### PR TITLE
Unit 7: Testing & Completion

### PR DESCRIPTION
**Pull request by chuckfecht**
Pull request for completion of testing of the Intern Onboarding Project

### CODE REVIEW

**Comment by jakekemple** [comment]
Not sure if you are waiting for another review on this, but e2e tests are still failing.

Here is the stack trace I received:

`[22:46:44] 'e2e' errored after 145 ms
[22:46:44] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/orchestrator/index.js:264:8)
    at /Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[22:46:44] E/local - Error code: 135
[22:46:44] E/local - Error message: No selenium server jar found at the specified location (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar). Check that the version number is up to date.
[22:46:44] E/local - Error: No selenium server jar found at the specified location (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar). Check that the version number is up to date.
    at Local.addDefaultBinaryLocs_ (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/built/driverProviders/local.js:43:19)
    at Local.setupEnv (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/built/driverProviders/local.js:73:14)
    at Runner.run (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/built/runner.js:261:37)
    at TaskRunner.run (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/built/taskRunner.js:108:27)
    at createNextTaskRunner (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/built/launcher.js:221:28)
    at /Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/protractor/built/launcher.js:248:13
    at _fulfilled (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/q/q.js:796:13)
    at /Users/jakekemple/Desktop/chuck-fecht-ux-iop/node_modules/q/q.js:604:44
[22:46:44] E/launcher - Process exited with error code 135

/Users/jakekemple/Desktop/chuck-fecht-ux-iop/gulpfile.js:37
		.on('error', function (e) { throw e })
		                            ^
Error: protractor exited with code 135`

If this is because of something I don't have, that you do have locally (selenium server or something?), it needs to be added to the readme. It could be an issue local to my machine if you still do not get the issue, and that would best be figured out if @jackvangent, @rjpepmeyer, or @rginther gets a second pair of eyes on it and one of them don't have the same experience.

The project & unit tests look good though

**Comment by rginther** [comment]
I get the same error that Jake mentioned.. also noticed a few other small details:
1) There are still some console logs laying around
2) There are some variables that aren't camel cased, but probably should be (We usually do with most of our variables), for instance, "tempurl", would look like "tempUrl", which is easier to read.

Other than that, looks like the unit tests and code look good.

**Comment by chuckfecht** [comment]
@jakekemple @rginther Something with how the Selenium server is spawned from Gulp forced me to use the Selenium Jar instead. Maybe run `webdriver-manager update` and try again?

**Comment by jakekemple** [comment]
@chuckfecht I tried that before posting my comment, didn't change anything unfortunately

**Comment by chuckfecht** [comment]
Do you the have [Java SDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) installed? 

Also I removed some files and managed to get the exact same error message, I ran `./node_modules/protractor/bin/webdriver-manager update`  instead of `webdriver-manager update` and got everything back in order.

**Comment by rjpepmeyer** [comment]
```
[17:22:06] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/ronaldpepmeyer/Repositories/chuck-fecht-ux-iop/node_modules/orchestrator/index.js:264:8)
    at /Users/ronaldpepmeyer/Repositories/chuck-fecht-ux-iop/node_modules/orchestrator/index.js:275:23
    at finish (/Users/ronaldpepmeyer/Repositories/chuck-fecht-ux-iop/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/ronaldpepmeyer/Repositories/chuck-fecht-ux-iop/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[17:22:06] I/local - Starting selenium standalone server...
[17:22:06] I/launcher - Running 1 instances of WebDriver
[17:22:07] I/local - Selenium standalone server started at http://192.168.0.104:57273/wd/hub
Started
.......
7 specs, 0 failures
Finished in 6.763 seconds
[17:22:16] I/local - Shutting down selenium standalone server.
[17:22:16] I/launcher - 0 instance(s) of WebDriver still running
[17:22:16] I/launcher - chrome #01 passed
```
So after running `./node_modules/protractor/bin/webdriver-manager update` like you said, it gets the error, but runs the tests. Aside from the already mentioned improvements, it looks good to me. All functionality in the site looks great, I didn't get any bugs or errors. I looked over the tests and didn't see any problems. I don't think the error should be an issue if the tests run as expected – but you should get a second opinion on that.

**Comment by rginther** [comment]
@chuckfecht, it actually would make way more sense to just auto-update webdriver-manager inside the gulp file, that way people won't have to do it manually. This is actually the approach we most often use in production gulp files.

**Comment by chuckfecht** [comment]
@rginther How would i go about that? I can't seem to find anything in platform-ux that references updating webdriver from within a gulp task.

**Comment by rginther** [comment]
Either Helpdesk or Reports should have a good example. Here is the Helpdesk example: https://github.com/Banno/helpdesk-ux/blob/master/gulpfile.js#L409

**Comment by chuckfecht** [comment]
Thanks @rginther. Tried using the example from Helpdesk, I'm getting the error

> Error: Task e2e requires a function that is a function

**Pull request merged**
